const actionTypes = Object.freeze({
     //app
     APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
     SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
     CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
     //user
     ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
     USER_LOGIN_SUCCESS: 'ADD_USER_SUCCESS',
     USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
     PROCESS_LOGOUT: 'PROCESS_LOGOUT',
     //admin
     GET_PENDING_USER: 'GET_PENDING_USER',
     GET_PENDING_USER_SUCCESS: 'GET_PENDING_USER_SUCCESS',

     CREATE_UPDATE_USER_PENDING_SUCCESS: 'CREATE_UPDATE_USER_PENDING_SUCCESS',
     CREATE_UPDATE_USER_PENDING_FAILED: 'CREATE_UPDATE_USER_PENDING_FAILED',

     GET_ALL_TRANSITIONS: 'GET_ALL_TRANSITIONS',
     GET_ALL_TRANSITIONS_SUCCESS: 'GET_ALL_TRANSITIONS_SUCCESS',
     GET_ALL_TRANSITIONS_FAILED: 'GET_ALL_TRANSITIONS_FAILED',

     GET_ALL_COLLECTIONS: 'GET_ALL_COLLECTIONS',
     GET_ALL_COLLECTIONS_SUCCESS: 'GET_ALL_COLLECTIONS_SUCCESS',
     GET_ALL_COLLECTIONS_FAILED: 'GET_ALL_COLLECTIONS_FAILED',
});
export default actionTypes;
